### ISSUE TITLE
Error after submit & download

### ISSUE THREAD

**Issue by dchassin** [slacgismo/generic-converters#5]
Run `main.py` (see #4 for why `app.py` doesn't work).  Select the file `test_IEEE_13_NR.json` and click `Submit & Download`.  The result is 
~~~
FileNotFoundError: [Errno 2] No such file or directory: './uploads/test_IEEE_13_NR.json'
~~~
followed by a traceback.

**Comment by jongoncalves** [comment]
Closing this out. Not able to repro in the `to_from_field` branch which will be merged in soon.
